### ISSUE TITLE
Slow page loading and Floating menu bar

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#302] opened 2023-04-21 10:24 UTC
Hi @BirenRathod @DavidRoy 

A recorder has pointed out the pointless floating menu bar that appears on the website and obscures content.

As a Site Admin, I see this menu bar, with several options related to managing the website. I didn't realise that the same menu bar is there for normal website users, but with no options and of no value.

![image](https://user-images.githubusercontent.com/24699793/233612796-c60dfa2a-81f9-48eb-85e6-e49c61589fe9.png)

Could we please remove this? It is a hindrance (and confusing) to most users.

This is in addition to complaints about the slow process of data entry - for which Biren is providing more details below.

Thanks, Ian

**Comment by BirenRathod** [comment] 2023-04-21 10:30
@johnvanbreda or @Gary-van-Breda Can you picked up this?

I found two errors.
1. Notice: ob_end_clean(): failed to delete buffer. No buffer to delete in iform_node_view() (line 552 of /code/web/modules/custom/iform/iform.module) 
2. #0 /code/web/modules/custom/iform/client_helpers/prebuilt_forms/ukbms_sectioned_transects_input_sample_2.php(766): data_entry_helper::load_existing_record(Array, 'sample', '21723445', 'detail', false, true)

look at drupal log https://ukbms.org/admin/reports/dblog/event/826979 & https://ukbms.org/admin/reports/dblog/event/826980

**Comment by BirenRathod** [comment] 2023-04-21 10:41
@johnvanbreda I also found this relate to verification rule -> https://ukbms.org/iform/ajax/ukbms_sectioned_transects_input_sample_2/check_verification_rules/284?location_id=2441&taxon_meaning_id=127703&survey_id=64&date=2023-04-20&nonce=aade52d1b1cd458ec59d5113d0819222a882f9a7&auth_token=2898c9555d4b12b0fd4e3c883ec3f2e050a41acc

Due to that the page load on this (https://ukbms.org/input-data?location_type_id=777&sample_id=21722336) is very slow.

**Comment by BirenRathod** [comment] 2023-04-21 11:37
@IanMiddlebrook can you check again? The speed is much better now. That floating menu bar is a part of the UKBMS theme but more importantly for general users, the blue icon is the log-out button. It has now disappeared as I cleared the cache now.

**Comment by IanMiddlebrook** [comment] 2023-04-21 12:11
Thanks @BirenRathod  I think the menu bar now remains at the top of the page, rather than floating?
Clicking the blue icon takes you to the home page, though there's no indication that's what it does. You need to hover on the blue icon to get the logout option. They can also logout under 'My Account' on the proper menu at the top of the page.
Website speed - it's just taken me about 40 seconds to load up the second data entry page for a new sample - that's not unusual, but still not great for volunteers.

**Comment by BirenRathod** [comment] 2023-04-21 12:51
@IanMiddlebrook I have now disabled the menu bar for all users only available for admin. Also, can you check again the speed? I checked by masquerading as "Crawford" & "Admin", the speed is much better now.

**Comment by IanMiddlebrook** [comment] 2023-04-21 13:04
Thanks @BirenRathod that's removed the menu bar for normal users. The only downside to this, for Admin, is we lose the 'Unmasquerade' option at the top of the page, so need to log out and log back in again. That was on the black line at the very top of the page, which also now disappears when we masquerade.

Speed - yes, this time the second page loaded up in 18 secs - so certainly improved.

**Comment by BirenRathod** [comment] 2023-04-21 13:23
@IanMiddlebrook I have added the unmasquerade link to "My account" now.

**Comment by IanMiddlebrook** [comment] 2023-04-21 13:25
Brilliant - thanks @BirenRathod

**Comment by RachaelConway** [comment] 2023-04-24 09:37
@BirenRathod @IanMiddlebrook 
 Hi both, please see feedback below from a user

**Several of us have had trouble entering our results this week, and we have ended up with multiple empty walks on the same day, as the data is repeatedly refused by the system.**

Will these walks need to be deleted by each user? Or is there a quicker method of removing the 'empty' walks please?

**Comment by BirenRathod** [comment] 2023-04-24 09:55
@RachaelConway Sorry for the inconvenience caused by another request we had on Saturday. 

@IanMiddlebrook Are you able to do this? let me know if not and we could find some other way to resolve this.

**Comment by IanMiddlebrook** [comment] 2023-04-24 10:10
I have a list of 61 duplicated transect walks that I will delete individually.

**Comment by RachaelConway** [comment] 2023-04-24 10:43
Thanks Ian

**Comment by RachaelConway** [comment] 2023-04-24 13:43
Hi @BirenRathod @IanMiddlebrook  I seem to have lost the masquerade function entirely

**Comment by IanMiddlebrook** [comment] 2023-04-24 13:47
Hi @RachaelConway 
You should have it here on the People page:
![image](https://user-images.githubusercontent.com/24699793/234015827-9a99622e-a859-44f0-93d8-00940879994d.png)

**Comment by RachaelConway** [comment] 2023-04-24 15:23
Its back now - thanks

**Comment by RachaelConway** [comment] 2023-04-24 15:44
@BirenRathod @IanMiddlebrook Sorry this isn't resolved. Masquerade appears as an option in the list view , after search and select of a user the drop down disappears

![image](https://user-images.githubusercontent.com/88440885/234048075-e0698417-3f3e-4b6d-920e-42076b51051e.png)

**Comment by IanMiddlebrook** [comment] 2023-04-24 15:47
Actually, I think it's disappeared for any user who has 'branch co-ordinator' role?

**Comment by DavidRoy** [comment] 2023-04-24 15:51
As an aside, this issue now covers ~3 separate things.  It is helpful to have separate issues for each separate thing, so that they are actionable (and closable!) and the flow of comments is easier to follow.....

**Comment by BirenRathod** [comment] 2023-04-24 16:22
@RachaelConway It disappeared because, after the masquerade, you need to unmasquerade first and then masquerade to another user.

**Comment by BirenRathod** [comment] 2023-04-24 16:24
@RachaelConway  you can use masquerade features from the home page too. It appears below the second twitter block.

**Comment by BirenRathod** [comment] 2023-04-24 17:38
@IanMiddlebrook Can you close this please if resolved?

**Closed as completed** 2023-04-25 08:25 UTC
Labels: bug, Website
