### ISSUE TITLE
Printing charts

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#248] opened 2021-09-27 10:29 UTC
Hi @DavidRoy 

We are often asked if it's possible to print the charts on the website, or at least copy the chart image into an editor.
We usually suggest using Print-Screen options, but this only works if you can see everything you want to print on the screen.

Is it possible to have 'print chart' options for each of the charts (Summary Chart, Estimate Chart, Section Plot, Year by Year Index Plot)?

Thanks, Ian

**Comment by Gary-van-Breda** [comment] 2022-02-01 08:09
@IanMiddlebrook : "Copy chart to clipboard" button added to both summary and estimates charts on Annual Summary, Section plot and Year plot forms. This matches the "Copy table to clipboard" button on the table tabs on the Annual Summary.

Note that due to technical restrictions, this will not work with Firefox (and I've changed the button label in this case). I've checked its OK on Chrome and Edge.

Deployed to Test for review.

**Comment by IanMiddlebrook** [comment] 2022-02-01 09:07
Hi @Gary-van-Breda 

This is not working for me in Chrome (Version 97.0.4692.99 ).
The Summary Table, Estimate Table and Raw Data all copy to clipboard fine, but the two Charts do not copy to clipboard.

**Comment by Gary-van-Breda** [comment] 2022-02-01 09:31
I've cleared the Drupal and Indicia Caches. I've got the same Chrome version.

@IanMiddlebrook : Could you try again?

**Comment by IanMiddlebrook** [comment] 2022-02-01 09:53
Hi @Gary-van-Breda 

Well I've managed to copy a chart to clipboard now. It seems very temperamental though. 
Once I've loaded up data, I can copy a chart if it's the first thing I try to copy to clipboard, but if I start copying various tables to clipboard and then try to copy another chart, It doesn't seem to work any more.

**Comment by Gary-van-Breda** [comment] 2022-02-01 10:14
Hi @IanMiddlebrook : are you having problems with all 3 forms, or just one of them?

**Comment by IanMiddlebrook** [comment] 2022-02-01 10:18
Hi @Gary-van-Breda 
The Summary Table, Estimate Table and Raw Data grids all copy to clipboard without any trouble. 
The Summary Chart and Estimate Chart are temperamental and only seem to copy to clipboard at first attempt, but not after I've copied something else.

**Comment by Gary-van-Breda** [comment] 2022-02-01 10:42
Hi @IanMiddlebrook : does it happen with the Section and Year plot forms?

**Comment by IanMiddlebrook** [comment] 2022-02-01 11:01
Sorry @Gary-van-Breda , I hadn't checked those.

They seem to be fine, except for one strange thing - they only seem to work/update at the second time of asking.
i.e, if I load up data for a site and select a couple of species, I can copy the chart to clipboard. If I then change the two species, and try to copy the chart, it just gives me the previous chart on my clipboard, but if I try again ,it's OK.
It seems like you need to hit the button twice to copy the new chart to clipboard.

There are a few other pages that act like this - eg loading up All Sites or My Sites, the first time you click to 'edit' a site, nothing happens, but then if you click again it's all fine.

**Comment by Gary-van-Breda** [comment] 2022-02-01 14:09
@IanMiddlebrook : I've put in some better feedback when copying the Annual summary charts, to mirror the Section and Year plots - the button text is changed whilst the copy is taking place. Can you confirm that the copy message is or isn't being displayed the times when the copy fails?
(I'm don't seem to be able to replicate this problem).

The general comment - these are all links (HTML <a> tags) - I'll look into further about having to click twice.

**Comment by IanMiddlebrook** [comment] 2022-02-01 14:38
Hi @Gary-van-Breda 

Yes, I think this is good, and probably highlights my problem - I was pasting before the copying had completed. Hadn't realised it might take so long (if only a few seconds).

Thanks, Ian

**Comment by Gary-van-Breda** [comment] 2022-02-01 16:06
Now pushed to Live. Changes confirmed as deployed.
Closing

**Closed as completed by Gary-van-Breda** 2022-02-01 16:06 UTC
Labels: feature request
