### ISSUE TITLE
timeout on https://ukbms.org/my-sites

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/UKBMS-online#193] opened 2021-03-23 12:42 UTC
This page does not load for me, nor when masquerading as other recorders. I get
The application did not respond in time.

**Comment by BirenRathod** [comment] 2021-03-23 13:35
@DavidRoy I don't see that problem by masquerading as you. Of course I checked after I cleaned the cache.

**Comment by Gary-van-Breda** [comment] 2021-04-12 14:22
@DavidRoy : Are you happy to close this as a duplicate of #207?

**Closed as completed** 2021-04-12 15:05 UTC
