### ISSUE TITLE
Magpie and Magpie Moth

### ISSUE THREAD

**Issue by zrandle** [BiologicalRecordsCentre/UKBMS-online#58] opened 2017-10-31 12:20 UTC
Can we have a blanket common name change for Magpie (the moth) to Magpie Moth Abraxas grossulariata to avoid potential data entry error and confusion?  

Under the other taxa list Magpie <Pica pica> is listed as is Magpie. Magpie moth is also listed as Magpie <Abraxas grossulariata>. Under the moth taxa list Magpie Moth is listed as Magpie Abraxas grossulariata and Magpie Moth Abraxas grossulariata.

Does this make sense? Thanks Zoe

**Comment by Gary-van-Breda** [comment] 2018-12-31 10:22
@johnvanbreda
This is in the UK Master List: the default common name is set to Magpie - how do we go about changing this? The use of the plain "Magpie" as a common name is confusing.

**Comment by johnvanbreda** [comment] 2019-01-02 09:40
@DavidRoy @kitenetter do you both agree that we should ask Chris to make a wider change, removing the common name Magpie from the moth so it can only be entered as Magpie Moth?

**Comment by kitenetter** [comment] 2019-01-02 11:36
I would strongly support this change!

**Magpie Moth**
For Abraxas grossulariae, UKSI gives the preferred English name as "Magpie", but it also has a non-preferred English name as "Magpie Moth":
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000168634

So one option would be for Chris to simply change which English name is considered preferred.

**Horse Chestnut Moth**
Can I add a similar request for the moth Pachycnemia hippocastanaria - can we change that to "Horse Chestnut Moth" instead of "Horse Chestnut". UKSI only has the latter option at the moment, so this would need a new name in the UKSI:
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000167832

(Personally I would prefer to see "Horse-chestnut Moth" with a hyphen, but traditionally the moth has always been "Horse Chestnut" as far as I know.)

[Edit - will transfer soldierfly name request over to iRecord, hadn't noticed this was the UKBMS issues page]

**Comment by DavidRoy** [comment] 2019-01-02 16:20
very happy to defer to Martin on this, thanks

**Comment by johnvanbreda** [comment] 2019-01-03 15:14
@kitenetter Can you get Chris to confirm the changes he will make to UKSI please? I don't really want to get out of step. 
Also, if we leave "Horse-Chestnut" and "Magpie" in as common names, then unless marked as redundant they will still be available for data entry in iRecord (and hence the cause of many errors). Would it be acceptable to mark these as redundant in UKSI?

**Comment by kitenetter** [comment] 2019-01-24 12:45
@johnvanbreda @DavidRoy Sorry, thought I'd emailed Chris previously but I hadn't, have done so now.

**Comment by kitenetter** [comment] 2019-01-26 09:31
Chris says (25 Jan):

> I have swapped over "Magpie" to be a vernacular junior synonym and now Magpie Moth is the recommended vernacular. I will also mark it as blocked for data-entry, as per John's advice. I'll do a similar operation with Horse Chestnut when I have added the "Moth" variant! 

I will update again once we know the TVK etc. for the new Horse Chestnut Moth name.

**Comment by DavidRoy** [comment] 2020-05-21 10:47
Closing as the general change is made

**Closed as completed by DavidRoy** 2020-05-21 10:47 UTC
