### ISSUE TITLE
Walks not appearing in calendar/duplicate walks in calendar

### ISSUE THREAD

**Issue by RachaelConway** [BiologicalRecordsCentre/UKBMS-online#317] opened 2023-07-25 13:42 UTC
@DavidRoy 

Hi I have had several reports this week of users submitting walks but not able to see them in the calendar. Some users have then resubmitted walks resulting in duplication. 

Two users have reported that walks submitted when the website was slow resulted in walks with with missing data

**Comment by RachaelConway** [comment] 2023-07-25 15:04
I think the system is also duplicating walks. Three users report having deleted one of the duplicates, they found the two were deleted off the system, resulting in no walks remaining.  Reports are from WCBS users only.

**Comment by DavidRoy** [comment] 2023-07-25 16:02
@JimBacon could you pick this one up please

**Comment by JimBacon** [comment] 2023-07-25 16:15
Hi @RachaelConway 
I'd like to begin by seeing if I can get any clues about this from the database contents.
Are you able to provide me with information sufficient for me to locate the records? 
For example, date/time, location and recorder.

Also, can you confirm the records are being submitted via the website? There is not a mobile app, is there?

**Comment by RachaelConway** [comment] 2023-07-26 08:36
Hi @JimBacon 

There is no app for UKBMS - website submissions only.  

Please see  examples of users and the walks impacted below.  There were others but there walks are now deleted as when the user deleted a duplicate, both walks were deleted off the system

Indicia Warehouse User ID 173017
<img width="859" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/4b0e82cf-c5c5-4694-bc51-4902aa7c2b9c">

Indicia Warehouse User ID
135295
<img width="717" alt="image" src="https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/88440885/3f3a769d-e22b-4dc8-b644-617acc995d14">

**Comment by JimBacon** [comment] 2023-07-26 08:47
Thanks. While I am following those leads, if you can get me any more information about the cases where both walks were deleted that would be very helpful. Even though it is not visible, the data will still be in the database and will give me clues. User ID, location name and date of survey, as above, would perfect if you have it.

**Comment by RachaelConway** [comment] 2023-07-26 08:57
Indicia Warehouse User ID  170082    TL9354 transect for the 18th July

**Comment by JimBacon** [comment] 2023-07-26 10:04
Examining the database shows
 - for user 173017 on 20/7 at SO9008
    - sample 22995215 was created on 2023-07-21 08:35:22 and was deleted on 2023-07-25 15:35:24
    - sample 22995318 was created on 2023-07-21 08:43:25
    - sample 23016811 was created on 2023-07-22 15:16:16 and was deleted on 2023-07-25 15:33:43

 - for user 135295 on 20/7  at Marbury
   - sample 22988169 was created on 2023-07-20 17:55:40
   - sample 22988953 was created on 2023-07-20 18:42:33 and was deleted on 2023-07-20 18:51:20

 - for user 170082 on 18/7 at TL9354 
   - sample 22938673 was created on 2023-07-19 10:16:30 and was deleted on 2023-07-22 17:09:43
   - sample 23018129 was created on 2023-07-22 17:03:25

The impression I am receiving is that creating and deleting records are working as expected but that the list of walks is not presenting them as expected. On the one hand, we have two users who add records, do not see them appearing, so add them again creating duplicates. On the other hand, we have a user who deletes a record and thinks both have gone. In fact one is still present
![image](https://github.com/BiologicalRecordsCentre/UKBMS-online/assets/2545390/03cad3bf-4246-4d58-9cb5-1846332ce399)

**Comment by RachaelConway** [comment] 2023-07-26 10:08
Hi Jim, the TL9354 walk was definitely not presenting on the calendar yesterday, so that is very curious. I'll send you the users email if that helps?

**Comment by RachaelConway** [comment] 2023-07-26 10:09
>On the 19th July I entered data for the TL9354 transect for the 18th 
>July without any problems and then saved it. It took me back to the ‘My Walks’
>calendar screen but I could not see any entry for the 18th. I then had 
>lots of problems trying to access the ‘My Data’ pages getting error 
>messages saying the server was not available.
> 
>I left things for a few days in case there was a technical problem and 
>tried again today to see my entry for the 18th July on the ‘My walks’ 
>page. The page displayed correctly but showed no entry for the 18th 
>July. I assumed my data had been lost so I re-entered all my data and 
>saved it, When I went back to the ‘My Walks’ page it now showed two 
>entries for the 18th July so the original data was there all along. I 
>therefore deleted my most recent entry but now both entries for the 18th have disappeared.
>

**Comment by JimBacon** [comment] 2023-07-26 16:05
I can't reproduce the problem. It is working fine for me. I do notice that, when you delete a BBS survey, the walks page is displayed next with Transects shown rather than WCBS-BBS. It would be easy not to notice and to think all your BBS records have gone. Probably the recorders are too experienced to be caught out by that.

We have an indication that the servers may have been under pressure at the time of the problems, perhaps meaning they would fail to return information, thus leaving web pages showing something erroneous. However, a bit of a look in the indcia warehouse log does not show any evidence of problems around 2023-07-21 08:35 or 2023-07-19 10:16. I am also wondering about caches somehow presenting out of date information. 

Unfortunately I don't have enough to go on here to proceed any further. Unless you are still getting reports of the problem, my best guess is that there was some transient neteowrk issue, We'll just have to monitor the situation for now and see if it recurs.

**Comment by RachaelConway** [comment] 2023-07-27 12:17
Hi Jim, 

I think both of your possible scenarios might be at play. A couple of users were new to UKBMS and may have been caught out by the default transect calendar. I did also receive several reports of slow performance last week. Thanks for your efforts.

**Comment by JimBacon** [comment] 2023-07-27 12:42
Shall we close this for now, then? Perhaps you could enlist the help of those recorders who experienced problems to keep a watch on this for us. If at any time they either

1. add a walk which does not then appear in the list or
2. add a walk which appears twice in the list

could they let us know before attempting to enter again or delete. It is also helpful to know the time they experience the problem as accurately as possible.

To reassure myself we are not overlooking a widespread problem, a count of the number of transect records over the past week gives the following. We'd surely be getting far more complaints if everyone was having the same trouble don't you think?
 
Date | Day| Number of walks recorded
---|---|---
19th July|Wed|213
20th July|Thu|269
21st July|Fri|198
22nd July|Sat|161
23rd July|Sun|191
24th July|Mon|185
25th July|Tue|242
26th July|Wed|361

**Closed as completed** 2023-07-27 13:48 UTC
Labels: bug, urgent
