### ISSUE TITLE
Raw Data table - difficult to see dates

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#185] opened 2021-03-01 16:24 UTC
Hi,

In the Raw Data tables under Annual Summary, the dates at the top of the columns are difficult to see. 
I guess they have defaulted to blue because they are hyperlinks, but difficult to see on  purple background.

Thanks,

Ian

**Comment by Gary-van-Breda** [comment] 2021-04-19 09:55
@IanMiddlebrook : I've changed the "look and feel" of the data grids in the Annual summary page (summary, estimates and raw data) to more closely match that of the data grids on the various "Sites" and "Walks" pages, though I've left the cell borders in (because there are a lot of columns, and it makes it easier to see which column/row a data item is in). This has changed the colour of background of the headers to a light grey, so the contrast is much better.

**Comment by IanMiddlebrook** [comment] 2021-04-19 10:04
Thanks @Gary-van-Breda

**Comment by IanMiddlebrook** [comment] 2021-09-15 08:14
Hi @Gary-van-Breda @DavidRoy 

Since the switch to Drupal 9 earlier this week, this problem has re-appeared - the links on the Raw Data tab are back to Blue on a Purple background.

Thanks, Ian

**Comment by DavidRoy** [comment] 2021-09-15 08:32
@BirenRathod can you look at this please

**Comment by BirenRathod** [comment] 2021-09-15 11:29
@DavidRoy & @IanMiddlebrook I changed the text colour now, so it should be clearly visible.

**Comment by Gary-van-Breda** [comment] 2022-02-01 08:03
@IanMiddlebrook : Pre-Drupal 9 look and feel re-instated: Annual Summary header colours changes, and link colours also changed to suit. Deployed to Test for review

**Comment by IanMiddlebrook** [comment] 2022-02-01 09:08
Thanks @Gary-van-Breda, looks good

**Comment by Gary-van-Breda** [comment] 2022-02-01 16:05
Now pushed to Live. Changes confirmed as deployed.
Closing

**Closed as completed by Gary-van-Breda** 2022-02-01 16:05 UTC
Labels: Fixed
